# -*- coding: utf-8 -*-
"""Assignment #3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ervYhqtKumcB7PmCl9b2RUKCyOJxYaIo

##Activity 1
"""

#imports math functions 
import math

#creates class that changes font and style of the warnings  
class w_aesthetic:
  def __init__(self, color, b, u, end):
    self.color = color
    self.b = b
    self.u = u
    self.end = end 
  
  def func(self):
    print(self.color + self.b + self.u + "For all inverse trig functions, input numbers from -1 to 1" + self.color + self.b + self.u + self.end)
    print("\n")

    print(self.color + self.b + self.u + "**ALL RESPONSES ARE CASE SENSITIVE**" + self.color + self.b + self.u + self.end)
    print("\n")
#method that uses ANSI values in the class 
des = w_aesthetic('\033[91m', '\033[1m', '\033[4m', '\033[0m')
des.func()

#creates class that changes font and style of the intro
class i_aesthetic:
  def __init__(self, color, b, u, i, c_end, i_end):
    self.color = color
    self.b = b
    self.u = u
    self.i = i 
    self.c_end = c_end
    self.i_end = i_end  
  def func(self):
    print(self.color + self.b + self.u + self.i + "             WELCOME TO ALEXIS'S CALCULATOR" + self.color + self.b + self.u + self.c_end + self.i_end)
    print("\n")

#method that uses ANSI values in the class   
des = i_aesthetic('\033[36m', '\033[1m', '\033[4m', '\x1B[3m','\033[0m', '\x1B[0m')
des.func()

#prints all the operations offered 
print("\n")
print("Operations")
operations = ["1. Addition", "2. Subtractions", "3. Division", "4. Multiplication", "5. Exponentiation", "6. Root", "7. Sine", "8. Inverse Sine", "9. Cosine", "10. Inverse Cosine"]

for x in operations: 
  print(x)
print("\n")


print("\n")

#method that takes request from user and executes it  
def ops():
  ans = int(input("Please enter a number (1/2/3/4) for your choice: "))

#methods for each operation with built-in conditionals to continue 
  if ans == 1: 
    def add():
      a_1 = float(input("First number: "))
      a_2 = float(input("Second number: "))
      sum_a = (a_1 + a_2)
      print("The sum is " + str(sum_a))
      print("\n")
          
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")        
    add()
  
  elif ans == 2: 
    def sub():
      s_1 = float(input("First number: "))
      s_2 = float(input("Second number: "))
      dif_a = (s_2 - s_1)
      print("The difference is " + str(dif_a))
      print("\n")
     
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    sub()
  
  elif ans == 3:  
    def div():
      d_1 = float(input("First number: "))
      d_2 = float(input("Second number: "))
      quo_a = (d_1/d_2)
      print("The difference is " + str(quo_a))
      print("\n")

      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    div()

  elif ans == 4:   
    def mult(): 
      m_1 = float(input("First number: ")) 
      m_2 = float(input("Second number: ")) 
      prod_a = (m_1 * m_2) 
      print("The product is " + str(prod_a)) 
      print("\n") 
          
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    mult()

  elif ans == 5:
    def exp():
      e_1 = float(input("First number: ")) 
      e_2 = float(input("Second number: ")) 
      sum_e = (e_1 ** e_2) 
      print("The answer is " + str(sum_e)) 
      print("\n") 
          
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    exp() 
  
  elif ans == 6: 
    def sq():
      sq_1 = float(input("First number: ")) 
      sq_2 = float(input("Second number/root: ")) 
      sum_sq = (sq_1 ** (1/sq_2)) 
      print("The root is " + str(sum_sq)) 
      print("\n")  
          
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    sq()  
  
  elif ans == 7:
    def si():
      si_1 = float(input("Degrees: "))
      trig_s = math.sin(math.radians(si_1))
      print("The sine is " + str(trig_s))
      print("\n") 
      
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    si() 

  elif ans == 8: 
    def isn():
      isn_1 = float(input("Enter the value: "))
      trig_isn = math.asin(isn_1)
      print("The inverse sine is " + str(trig_isn))
      print("\n")  
      
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you") 
    isn()

  elif ans == 9: 
    def co():
      c_1 = float(input("Degrees: "))
      trig_c = math.cos(math.radians(c_1))
      print("The cosine is " + str(trig_c))
      print("\n")  
     
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    co()

  elif ans == 10: 
    def ic():
      ic_1 = float(input("Enter the value: "))
      trig_ic = math.acos(ic_1)
      print("The inverse cosine is " + str(trig_ic))
      print("\n")   
      
      response = input("Do you want to continue? Y/N: ")
      print("\n")
      if response == "Y":
        ops()
      elif response == "N":
        print("Thank you")
      else: 
        print("Invalid input.")
        response = input("Do you want to continue? Y/N: ")
        print("\n")
        if response == "Y":
          ops()
        elif response == "N":
          print("Thank you")
    ic()

  else: 
    print("Invalid input. Please try again.")

#calls the method to begin the calculator 
ops()