# -*- coding: utf-8 -*-
"""Assignment #3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ervYhqtKumcB7PmCl9b2RUKCyOJxYaIo

##Activity 2
"""

#creates class that changes font and style of the warnings  
class w_aesthetic:
  def __init__(self, color, b, u, end):
    self.color = color
    self.b = b
    self.u = u
    self.end = end 
  
  def func(self):
    print(self.color + self.b + self.u + "**ALL RESPONSES ARE CASE SENSITIVE**" + self.color + self.b + self.u + self.end)
    print("\n")
    print(self.color + self.b + self.u + "**ALL ANSWERS ARE SUBJECT TO CHANGE BASED ON FLUCTUATING EXCHANGE RATES**" + self.color + self.b + self.u + self.end)
    print("\n")
#method that uses ANSI values in the class
des = w_aesthetic('\033[91m', '\033[1m', '\033[4m', '\033[0m')
des.func()

#creates class that changes font and style of the intro
class i_aesthetic:
  def __init__(self, color, b, u, i, c_end, i_end):
    self.color = color
    self.b = b
    self.u = u
    self.i = i 
    self.c_end = c_end
    self.i_end = i_end  
  
  def func(self):
    print(self.color + self.b + self.u + self.i + "           WELCOME TO ALEXIS'S CURRENCY CONVERTER" + self.color + self.b + self.u + self.c_end + self.i_end)
    print("\n")
#method that uses ANSI values in the class
des = i_aesthetic('\033[94m', '\033[1m', '\033[4m', '\x1B[3m','\033[0m', '\x1B[0m')
des.func()


#prints all the currencies offered
print("Currencies")
currencies = ["1. Euro", "2. Pound Sterling", "3. Franc", "4. Japanese Yen", "5. Australian Dollar", "6. Danish Krone", "7. South African Rand", "8. Russian Ruble", "9. Iraqi Dinar", "10. Czech Koruna"]

for x in currencies: 
  print(x)
print("\n")

print("\n")

#method that takes request from user and executes it  
def currs():
  ans = int(input("Please enter a number (1/2/3/4) for your choice: "))

#methods for each currency conversion with built-in conditionals to continue
  if ans == 1: 
    def euro():
      e = float(input("Enter USD Value: "))
      ce = float(e * 0.89)
      print(str(e) + " USD converted to Euros is " + str(ce))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    euro()

  if ans == 2: 
    def pound():
      p = float(input("Enter USD Value: "))
      cp = float(p * 0.75)
      print(str(p) + " USD converted to Pound Sterlings is " + str(cp))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    pound()

  if ans == 3: 
    def franc():
      f = float(input("Enter USD Value: "))
      cf = float(f * 0.93)
      print(str(f) + " USD converted to Francs is " + str(cf))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    franc()

  if ans == 4: 
    def yen():
      y = float(input("Enter USD Value: "))
      cy = float(y * 115.06)
      print(str(y) + " USD converted to Japanese Yen is " + str(cy))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    yen()

  if ans == 5: 
    def dollar():
      d = float(input("Enter USD Value: "))
      cd = float(d * 1.39)
      print(str(d) + " USD converted to Australian Dollars is " + str(cd))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    dollar()
  
  if ans == 6: 
    def krone():
      k = float(input("Enter USD Value: "))
      ck = float(k * 6.62)
      print(str(k) + " USD converted to Danish Krones is " + str(ck))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    krone()
  
  if ans == 7: 
    def rand():
      r = float(input("Enter USD Value: "))
      re = float(r * 15.88)
      print(str(r) + " USD converted to South African Rands is " + str(re))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    rand()
  
  if ans == 8: 
    def ruble():
      ru = float(input("Enter USD Value: "))
      cru = float(ru * 74.26)
      print(str(ru) + " USD converted to Russian Rubles is " + str(cru))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    ruble()
  
  if ans == 9: 
    def dinar():
      di = float(input("Enter USD Value: "))
      cdi = float(di * 1459.50)
      print(str(di) + " USD converted to Iraqi Dinar is " + str(cdi))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    dinar()
  
  if ans == 10: 
    def koruna():
      ko = float(input("Enter USD Value: "))
      cko = float(ko * 22.71)
      print(str(ko) + " USD converted to Czech Koruna is " + str(cko))
      print("\n")
          
      response = input("Do you want to convert more? Y/N: ")
      print("\n")
      if response == "Y":
        new = input("Do you want to see the options? Y/N: ")
        if new == "Y":
          for x in currencies: 
            print(x)
          print("\n")
          currs()
        elif new == "N":
          currs()
        else:
          print("Invalid input.")
      elif response == "N":
          print("Thank you")
      else: 
        print("Invalid input.")      
    koruna()

#calls method to begin the conversion
currs()